### ISSUE TITLE
token is not Refresh

### ISSUE THREAD

**Issue by Jumbo-WJB** [NetSPI/BurpExtractor#2]
I already send extractor And set it up
<img width="1255" alt="snipaste_2018-08-12_19-06-11" src="https://user-images.githubusercontent.com/7954518/44001358-3f6dba8e-9e63-11e8-8479-763048717534.png">
<img width="1228" alt="snipaste_2018-08-12_19-07-23" src="https://user-images.githubusercontent.com/7954518/44001359-3fa53540-9e63-11e8-8e9e-3d4e40973796.png">
<img width="987" alt="snipaste_2018-08-12_19-09-15" src="https://user-images.githubusercontent.com/7954518/44001361-3fe18806-9e63-11e8-977f-ea8bbc027374.png">

but，it is not work
<img width="1178" alt="snipaste_2018-08-12_19-07-49" src="https://user-images.githubusercontent.com/7954518/44001364-543b44b8-9e63-11e8-8f37-9621302266e6.png">
<img width="1197" alt="snipaste_2018-08-12_19-08-29" src="https://user-images.githubusercontent.com/7954518/44001365-547e3caa-9e63-11e8-838e-18286353ed85.png">

**Comment by wstrei** [comment]
Hey Jumbo-WJB, thanks for your question. From a quick look over everything, I'm not sure why this set up is not working for you. 

I just published a new release that might help you out. I added a debug button in the main Extractor tab which enables some logging which might help.

Hope that can help with the issue!

**Comment by Jumbo-WJB** [comment]
thanks!

**Comment by aph3rson** [comment]
@Jumbo-WJB did your issue get resolved, or are you still having issues with this?

**Comment by Jumbo-WJB** [comment]
The problem has been solved, thank you!
